### ISSUE TITLE
The output of voxblox_ground_truth 

### ISSUE THREAD

**Issue by yonggaogit** [engcang/cpp-reconstruction-application#1]
The map type of [voxblox_ground_truth] is TSDF map, how can I import it into cloudcompare?

**Comment by engcang** [comment]
Hi.

There are two options.
1. By simply adding few lines of code into `voxblox_ground_truth`, we can get `.pcd` file. `Cloudcompare` can get the `.pcd` file as input.
2. Use `voxblox_ros` to receive the generated `.tsdf` file, then try to call `map save` service of `voxblox_ros` node. It generates `.ply` file and `Cloudcompare` can get it as input.

**Comment by yonggaogit** [comment]
> Hi.
> 
> There are two options.
> 
>     1. By simply adding few lines of code into `voxblox_ground_truth`, we can get `.pcd` file. `Cloudcompare` can get the `.pcd` file as input.
> 
>     2. Use `voxblox_ros` to receive the generated `.tsdf` file, then try to call `map save` service of `voxblox_ros` node. It generates `.ply` file and `Cloudcompare` can get it as input.

I got it, thanks!
